export const produucts = [
  {
    id: 1,
    name: "Synthetine",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Jakarta",
    description:
      "Elegant minimalist chair with a sleek white design. Perfect for modern interiors and office spaces. Features a comfortable ergonomic design with high-quality materials for long-lasting durability.",
    image_url: "/images/synthetine_chair.jpg",
    availability: "In stock",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Leniesa",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Jakarta",
    description:
      "Contemporary gray chair with a unique curved design. Combines both style and comfort with premium upholstery and sturdy construction. Ideal for dining rooms or as an accent piece.",
    image_url: "/images/leniesa_chair.jpg",
    availability: "In stock",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Lolita",
    price: 7000000,
    original_price: 14000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Sofa",
    status: "Sale",
    tag: "-50%",
    location: "Jakarta",
    description:
      "Luxurious white tufted sofa with elegant design. Features plush cushioning and premium fabric for ultimate comfort. Perfect centerpiece for any living room with its timeless appeal and sophisticated style.",
    image_url: "/images/lolita_sofa.jpg",
    availability: "In stock",
    rating: 4.9,
  },
  {
    id: 4,
    name: "Respira",
    price: 900000,
    original_price: 900000,
    currency: "Rp",
    discount_percentage: 0,
    category: "Living Room Set",
    status: "New",
    tag: "New",
    location: "Jakarta",
    description:
      "Modern living room furniture set with natural materials and earth tones. Creates a cozy and inviting atmosphere with its balanced design. Includes comfortable seating and complementary pieces for a cohesive look.",
    image_url: "/images/respira_livingset.jpg",
    availability: "In stock",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Synthetine",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Bandung",
    description:
      "Elegant minimalist chair with a sleek white design. Perfect for modern interiors and office spaces. Features a comfortable ergonomic design with high-quality materials for long-lasting durability.",
    image_url: "/images/synthetine_chair.jpg",
    availability: "In stock",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Leniesa",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Bandung",
    description:
      "Contemporary gray chair with a unique curved design. Combines both style and comfort with premium upholstery and sturdy construction. Ideal for dining rooms or as an accent piece.",
    image_url: "/images/leniesa_chair.jpg",
    availability: "In stock",
    rating: 4.5,
  },
  {
    id: 7,
    name: "Lolita",
    price: 7000000,
    original_price: 14000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Sofa",
    status: "Sale",
    tag: "-50%",
    location: "Bandung",
    description:
      "Luxurious white tufted sofa with elegant design. Features plush cushioning and premium fabric for ultimate comfort. Perfect centerpiece for any living room with its timeless appeal and sophisticated style.",
    image_url: "/images/lolita_sofa.jpg",
    availability: "In stock",
    rating: 4.9,
  },
  {
    id: 8,
    name: "Respira",
    price: 900000,
    original_price: 900000,
    currency: "Rp",
    discount_percentage: 0,
    category: "Living Room Set",
    status: "New",
    tag: "New",
    location: "Bandung",
    description:
      "Modern living room furniture set with natural materials and earth tones. Creates a cozy and inviting atmosphere with its balanced design. Includes comfortable seating and complementary pieces for a cohesive look.",
    image_url: "/images/respira_livingset.jpg",
    availability: "In stock",
    rating: 4.8,
  },
  {
    id: 9,
    name: "Synthetine",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Surabaya",
    description:
      "Elegant minimalist chair with a sleek white design. Perfect for modern interiors and office spaces. Features a comfortable ergonomic design with high-quality materials for long-lasting durability.",
    image_url: "/images/synthetine_chair.jpg",
    availability: "In stock",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Leniesa",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Surabaya",
    description:
      "Contemporary gray chair with a unique curved design. Combines both style and comfort with premium upholstery and sturdy construction. Ideal for dining rooms or as an accent piece.",
    image_url: "/images/leniesa_chair.jpg",
    availability: "In stock",
    rating: 4.5,
  },
  {
    id: 11,
    name: "Lolita",
    price: 7000000,
    original_price: 14000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Sofa",
    status: "Sale",
    tag: "-50%",
    location: "Surabaya",
    description:
      "Luxurious white tufted sofa with elegant design. Features plush cushioning and premium fabric for ultimate comfort. Perfect centerpiece for any living room with its timeless appeal and sophisticated style.",
    image_url: "/images/lolita_sofa.jpg",
    availability: "In stock",
    rating: 4.9,
  },
  {
    id: 12,
    name: "Respira",
    price: 900000,
    original_price: 900000,
    currency: "Rp",
    discount_percentage: 0,
    category: "Living Room Set",
    status: "New",
    tag: "New",
    location: "Surabaya",
    description:
      "Modern living room furniture set with natural materials and earth tones. Creates a cozy and inviting atmosphere with its balanced design. Includes comfortable seating and complementary pieces for a cohesive look.",
    image_url: "/images/respira_livingset.jpg",
    availability: "In stock",
    rating: 4.8,
  },
  {
    id: 13,
    name: "Synthetine",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Bali",
    description:
      "Elegant minimalist chair with a sleek white design. Perfect for modern interiors and office spaces. Features a comfortable ergonomic design with high-quality materials for long-lasting durability.",
    image_url: "/images/synthetine_chair.jpg",
    availability: "In stock",
    rating: 4.7,
  },
  {
    id: 14,
    name: "Leniesa",
    price: 2500000,
    original_price: 5000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Chair",
    status: "Sale",
    tag: "-50%",
    location: "Bali",
    description:
      "Contemporary gray chair with a unique curved design. Combines both style and comfort with premium upholstery and sturdy construction. Ideal for dining rooms or as an accent piece.",
    image_url: "/images/leniesa_chair.jpg",
    availability: "In stock",
    rating: 4.5,
  },
  {
    id: 15,
    name: "Lolita",
    price: 7000000,
    original_price: 14000000,
    currency: "Rp",
    discount_percentage: 50,
    category: "Sofa",
    status: "Sale",
    tag: "-50%",
    location: "Bali",
    description:
      "Luxurious white tufted sofa with elegant design. Features plush cushioning and premium fabric for ultimate comfort. Perfect centerpiece for any living room with its timeless appeal and sophisticated style.",
    image_url: "/images/lolita_sofa.jpg",
    availability: "In stock",
    rating: 4.9,
  },
  {
    id: 16,
    name: "Respira",
    price: 900000,
    original_price: 900000,
    currency: "Rp",
    discount_percentage: 0,
    category: "Living Room Set",
    status: "New",
    tag: "New",
    location: "Bali",
    description:
      "Modern living room furniture set with natural materials and earth tones. Creates a cozy and inviting atmosphere with its balanced design. Includes comfortable seating and complementary pieces for a cohesive look.",
    image_url: "/images/respira_livingset.jpg",
    availability: "In stock",
    rating: 4.8,
  },
];